# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ""

# The language of the webpage â€º http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: zh-CN

# Additional parameters for datetime localization, optional. â€º https://github.com/iamkun/dayjs/tree/dev/src/locale
prefer_datetime_locale: Asia/Shanghai

# Change to your timezone â€º http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone:

# jekyll-seo-tag settings â€º https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# â†“ --------------------------

title: Jo Cruise                         # the main title

tagline: This is Jo's space   # it will display as the sub-title

description: I write stuff.                   # used by seo meta and the atom feed

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'https://jo-cruise.github.io'

github:
  username: Jo-CRuiSe             # change to your github username

twitter:
  username:             # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Jo Cruise
  email: zhouzh2022@sjtu.edu.cn             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    # - https://twitter.com/username      # change to your twitter homepage
    - https://github.com/Jo-CRuiSe       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username


# Site Verification Settings
webmaster_verifications:
  google: '9j-yTP-3EvOXjKm1Xp70wKYyynAfgCIj7vY64gFDcBU' # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# â†‘ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID


# Pageviews settings
pageviews:
  provider: # now only supports 'goatcounter'


# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode:   # [light|dark]

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: ./assets/config/avatar.jpg

# boolean type, the global switch for ToC in posts.
toc: true

comments:
  active:        # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname:    # fill with the Disqus shortname. â€º https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings â€º https://utteranc.es/
  utterances:
    repo:         # <gh-username>/<repo>
    issue_term:   # < url | pathname | title | ...>
  # Giscus options â€º https://giscus.app
  giscus:
    repo: "Jo-CRuiSe/Jo-CRuiSe.github.io" # <gh-username>/<repo>
    repo_id: "R_kgDOKc2Mwg"
    category: "General"
    category_id: "DIC_kwDOKc2Mws4CZ8vP"
    mapping:          # optional, default to 'pathname'
    input_position:   # optional, default to 'bottom'
    lang:             # optional, default to the value of `site.lang`

  # Valine
valine_comment:
  enable: true  #æ˜¯å¦å¯ç”¨valine
  leancloud_appid: rzV27a2iZkM3qCAIMnz2u6pO-9Nh9j0Va  #LeanCloudåº”ç”¨çš„AppID
  leancloud_appkey: 6sPXQuSvQBiMk60c7sFhRPVz  #LeanCloudåº”ç”¨çš„AppKey
  placeholder: "ğŸ¥³å¿«æ¥å‘è¡¨ä¸€æ¡è¯„è®ºå§ï¼ï¼ˆå…è®¸åŒ¿åè¯„è®ºï¼‰\nğŸ“¨å‘¢ç§°å¡«å…¥QQå·å¯ä»¥è‡ªåŠ¨è¡¥å…¨é‚®ç®±å’Œæ˜¾ç¤ºå¤´åƒ \nğŸ“è¯·éµå®ˆç½‘ç»œé“å¾·"  #è¯„è®ºåŒºçš„å ä½æ–‡æœ¬
  avatar: 'mp'  #è¯„è®ºç”¨æˆ·çš„å¤´åƒ
  enableQQ: true
  visitor: true
  serverURLs: 'https://rzv27a2i.lc-cn-n1-shared.com'  #LeanCloudåº”ç”¨çš„REST API æœåŠ¡å™¨åœ°å€

# Self-hosted static assets, optional â€º https://github.com/cotes2020/chirpy-static-assets
# Self-hosted static assets, optional â€º https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: false # the option for PWA feature (installable)
  cache:
    enabled: false # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 5

mathjax:
  display_on_home:
    enabled: true # the option for math on home page
  packages:
    ams: true # the option for ams package
    amscd: true # the option for amscd package
    bbox: false # the option for bbox package
    boldsymbol: false # the option for boldsymbol package
    braket: true # the option for braket package
    bussproofs: false # the option for bussproofs package
    cancel: false # the option for cancel package
    cases: true # the option for cases package
    centernot: false # the option for centernot package
    color: false # the option for color package
    colorv2: false # the option for colorv2 package
    colortbl: false # the option for colortbl package
    configmacros: true # the option for configmacros package
    empheq: false # the option for empheq package
    extpfeil: false # the option for extpfeil package
    gensymb: false # the option for gensymb package
    mathtools: true # the option for mathtools package
    mhchem: false # the option for mathtools package
    newcommand: true # the option for newcommand package
    textcomp: false # the option for textcomp package
    physics: true # the option for physics package
    unicode: true # the option for unicode package
    upgreek: false # the option for upgreek package
    verb: false # the option for verb package
  other_packages: [] # the option for other packages, use comma to separate. i.e. [mhchem, textcomp]
  macros: 
    oiint: "{\\\\bigcirc}\\\\kern-11.5pt{\\\\int}\\\\kern-6.5pt{\\\\int}"

Leancloud:
  appId: 'rzV27a2iZkM3qCAIMnz2u6pO-9Nh9j0Va' # fill with your Leancloud appId
  appKey: '6sPXQuSvQBiMk60c7sFhRPVz' # fill with your Leancloud appKey
  serverURL: 'https://rzv27a2i.lc-cn-n1-shared.com' # fill with your Leancloud serverURL

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options â€º https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true
  - scope:
      path: ''
    values:
      seo_description_max_words: 200

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]


exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/


